apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: streaming-platform
type: Opaque
data:
  url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMuc3RyZWFtaW5nLXBsYXRmb3JtLmRldi5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL3N0cmVhbWluZ19wbGF0Zm9ybV9kYg==  # jdbc:postgresql://postgres.streaming-platform.dev.svc.cluster.local:5432/streaming_platform_db
  username: cG9zdGdyZXM=  # postgres
  password: cGFzc3dvcmQ=  # password

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: streaming-platform
type: Opaque
data:
  secret: c2VjdXJlSnNvbldlYlRva2VuU2VjcmV0S2V5Rm9yU3RyZWFtaW5nUGxhdGZvcm0=  # secureJsonWebTokenSecretKeyForStreamingPlatform
