version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: streaming-postgres
    environment:
      POSTGRES_DB: streaming_platform_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  catalog-service:
    build:
      context: ./streaming-catalog-service
      dockerfile: Dockerfile
    container_name: streaming-catalog-service
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/streaming_platform_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres-data:
