services:
  postgres:
    image: postgres:15-alpine
    container_name: streaming-postgres
    environment:
      POSTGRES_DB: streaming_platform_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # PostgreSQL exposed on 5433 for local connections
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  catalog-service:
    build:
      context: ./streaming-catalog-service
      dockerfile: Dockerfile
    container_name: streaming-catalog-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Enables 'application-docker.yml' inside Docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/streaming_platform_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
