# src/main/resources/application.yml
spring:
  application:
    name: streaming-catalog-service

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/streaming_catalog}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.examples.streaming_platform: DEBUG
    org.springframework: INFO