spring:
  application:
    name: streaming-catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5433/streaming_platform_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      locations: classpath:/schema/**
      printer:
        enabled: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST

  docker:
    compose:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  security:
    user:
          name: admin
          password: admin

server:
  port: 8082

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui


# In application.yml
app:
  use-resolvers: false  # Set to true if you want to use resolver classes instead of controllers