spring:
  application:
    name: streaming-catalog-service

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/streaming_platform_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  graphql:
    graphiql:
      enabled: true
      path: /schema
    path: /schema
  docker:
    compose:
          enabled: false


server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

dgs:
  graphql:
    schema-locations: classpath:/schema/**
