spring:
  application:
    name: streaming-catalog-service

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/streaming_platform_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
    schema:
      printer:
        enabled: true

server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs


logging:
  level:
    root: INFO
    com.examples.streaming_platform: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

